---
format:
    html:
        embed-resources: true
---

# Cleaning: Part-1: 

The goal now is to post process the job descriptions you collected in the Crawl

In this section you MUST do it manually using traditional data-science cleaning and parsing skills, i.e. without use of ANY LLM tools or wrappers.

The unit of analysis in this case is "job" 

Your job is to write a cleaning script to Parse the Crawl results and create a data-frame which will be saved to `data/processed-jobs-1.csv`, this data-frame will be used for later EDA. 


You should try to extract as many features as possible, here a possible suggestions. 

These features can provide a comprehensive overview when analyzing job postings for trends, patterns, and insights.

You will almost certainly not be able to extract all of these features, but do your best to make the most detailed data set that you can. You can also ADD more features to this list if they come to mind.

- **Job Title**
- **Company Name**
- **Sector/Industry**
- **Location** (City, State, Country)
- **Job Type** (Full-time, Part-time, Contract, Internship)
- **Salary** (Range or Exact)
- **Experience Level** (Entry-level, Mid-level, Senior-level)
- **Education Requirements** (Degree, Major, Certifications)
- **Skills/Technologies Required** (e.g., Python, SQL, Machine Learning, Cloud)
- **Job Responsibilities/Duties**
- **Required Years of Experience**
- **Benefits** (Health insurance, Retirement plans, Paid time off)
- **Remote Work Options** (Remote, Hybrid, On-site)
- **Application Deadline**
- **Job Posting Date**
- **Job Description Length** (Number of words or characters)
- **Keywords/Frequency of Terms**
- **Certifications Required or Preferred** (e.g., AWS Certified, PMP)
- **Team Size** (If mentioned)
- **Company Size** (Small, Medium, Large)
- **Company Reputation/Ranking** (If available)
- **Job Posting Platform** (Where the job was posted, e.g., LinkedIn, Indeed)
- **Company Values or Culture** (Diversity, Innovation, Sustainability)
- **Visa Sponsorship Availability**
- **Interview Process Information** (If mentioned)
- **Expected Start Date**
- **Job Posting Expiry Date**
- **Gender Diversity Language** (If any)
- **Working Hours/Shift Type** (Day shift, Night shift, Flexible hours)
- **Required Language Skills**
- **Job Location Proximity to Major Cities** (If provided)
- **Travel Requirements** (Percentage or Frequency)
- **Team Collaboration Tools Mentioned** (Slack, Zoom, etc.)
- **Reporting Line** (e.g., Reports to Senior Manager)
- **Job Benefits Related to Learning & Development** (e.g., Courses, Training)
- **Company Stock Options** (If offered)
- **Required Soft Skills** (e.g., Communication, Leadership)
- **Company Perks** (Gym membership, Free meals, Company car)
- **Job Posting ID or Reference Number**


While cleaning try to address the following as best you can

- **Missing Data**: Identify missing or null values in features like salary, company name, or location.
- **Duplicates**: Check for duplicate job listings or job descriptions.
- **Inconsistent Formatting**: Ensure consistency in categorical variables (e.g., job titles, location formats).
- **Data Type Validation**: Ensure each feature has the appropriate data type (e.g., salary as numeric, dates as datetime).
- **Outliers**: Detect outliers in salary, years of experience, or job description length.

In [1]:
import os
import json
import pandas as pd
import datetime
import re
json_files= '/Users/zp/hw-3-zp199717'
csv_file = '/Users/zp/hw-3-zp199717/data/processed-jobs-1.csv'

jobs = []

for filename in os.listdir(json_files):
    if filename.endswith('.json'):
        with open(os.path.join(json_files, filename), 'r') as file:
                job_data = json.load(file)
            
        jobs_results = job_data.get('jobs_results', [])
            

        jobs_results = job_data.get('jobs_results', [])
            
        for job in jobs_results:
                job_entry = {}
                job_entry['Job Title'] = job.get('title', '').strip()
                job_entry['Roles'] = 'Not Specified'
                job_entry['Company Name'] = job.get('company_name', '').strip()
                job_entry['Sector/Industry'] = job.get('industry', '').strip()
                job_entry['Location'] = job.get('location', '').strip()
                job_entry['Job Type'] = job.get('job_type', '').strip()
                job_entry['Salary'] = job.get('salary', '').strip()
                job_entry['Experience Level'] = job.get('experience_level', '').strip()
                job_entry['Education Requirements'] = job.get('education_requirements', '').strip()
                job_entry['Skills/Technologies Required'] = ', '.join(job.get('skills', [])).strip()
                job_entry['Job Responsibilities/Duties'] = job.get('description', '').strip()
                job_entry['Required Years of Experience'] = job.get('years_of_experience', '').strip()
                job_entry['Remote Work Options'] = job.get('remote', '').strip()
                job_entry['Job Description Length'] = len(job_entry['Job Responsibilities/Duties'])
                job_entry['Certifications Required or Preferred'] = ', '.join(job.get('certifications', [])).strip()
                job_entry['Visa Sponsorship Availability'] = job.get('visa_sponsorship', '').strip()
                job_entry['Working Hours/Shift Type'] = job.get('working_hours', '').strip()

                jobs.append(job_entry)

jobs_df = pd.DataFrame(jobs)
#check duplicates and drop it
jobs_df= jobs_df.drop_duplicates(subset=['Job Title', 'Job Responsibilities/Duties'], keep='first')

jobs_df.head()

,Job Title,Roles,Company Name,Sector/Industry,Location,Job Type,Salary,Experience Level,Education Requirements,Skills/Technologies Required,Job Responsibilities/Duties,Required Years of Experience,Remote Work Options,Job Description Length,Certifications Required or Preferred,Visa Sponsorship Availability,Working Hours/Shift Type
0,Technical Solutions Specialist,Not Specified,Figure Eight Federal,,United States,,,,,,Artificial Intelligence (AI) is transforming g...,,,3738,,,
1,AI API specialist to integrate TypingMind into...,Not Specified,Upwork,,Anywhere,,,,,,i have purchased and API code and such from Ty...,,,379,,,
2,"Solutions Architect, Generative AI Specialist",Not Specified,2100 NVIDIA USA,,United States,,,,,,Do you want to be part of the team that brings...,,,5140,,,
3,"Machine Learning Specialist, Trilogy (Remote) ...",Not Specified,Crossover,,Anywhere,,,,,,Ready to leverage your mastery of LLMs to driv...,,,2786,,,
4,Expert AI/Machine Learning Specialist Needed,Not Specified,Upwork,,Anywhere,,,,,,We are seeking a highly rated expert in AI and...,,,480,,,

In [2]:

jobs_df = jobs_df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

jobs_df.fillna('Not Specified', inplace=True)

jobs_df['Experience Level'] = jobs_df['Experience Level'].str.title()

jobs_df['Location'] = jobs_df['Location'].str.replace(r'\s*,\s*', ', ', regex=True)

jobs_df['Required Years of Experience'] = pd.to_numeric(jobs_df['Required Years of Experience'].str.extract(r'(\d+)')[0], errors='coerce')

jobs_df['Job Title'] = jobs_df['Job Title'].str.replace(r'\s+-.*$', '', regex=True).str.strip()

job_types = ['Full-Time', 'Part-Time', 'Contract', 'Internship']
for job_type in job_types:
    jobs_df.loc[jobs_df['Job Title'].str.contains(job_type, case=False, na=False), 'Job Type'] = job_type
jobs_df['Job Type'] = jobs_df['Job Type'].str.title().fillna('Not Specified')

remote_keywords = ['Remote','Hybrid','On-site']
for keyword in remote_keywords:
    jobs_df.loc[jobs_df['Job Title'].str.contains(keyword, case=False, na=False), 'Remote Work Options'] = keyword
jobs_df['Remote Work Options'] = jobs_df['Remote Work Options'].str.title().fillna('Not Specified')
jobs_df['Skills/Technologies Required'] = jobs_df['Skills/Technologies Required'].str.replace(r'[;,]', ',').str.title().str.strip()
jobs_df['Skills/Technologies Required'] = jobs_df['Skills/Technologies Required'].replace('', 'Not Specified')
jobs_df.fillna('Not Specified', inplace=True)

first_cleaning_df = jobs_df

/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/385592240.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  jobs_df = jobs_df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/385592240.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Not Specified' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  jobs_df.fillna('Not Specified', inplace=True)

In [3]:
# set roles(key name of the job title)
roles_keywords = [
    "Data Scientist", "Machine Learning Engineer", "Artificial Intelligence Specialist", "Data Analyst",
    "Business Intelligence Analyst", "Research Scientist (AI-ML)", "Deep Learning Engineer",
    "NLP Engineer (Natural Language Processing)", "Computer Vision Engineer", "Data Engineer",
    "Applied Scientist", "Quantitative Analyst (Quant)", "AI Solutions Architect", "Statistician",
    "Big Data Engineer", "Data Science Consultant", "Automation Engineer", "Analytics Manager",
    "Operations Research Analyst", "Robotics Engineer", "Bioinformatics Data Scientist",
    "Financial Data Scientist", "Customer Insights Analyst", "Marketing Data Analyst", 
    "Data Strategy Manager", "Cloud AI Engineer", "Computational Scientist", 
    "Fraud Detection Specialist", "Risk Analyst", "Data Architect","Specialist","Consultant"
]
for role in roles_keywords:
    first_cleaning_df.loc[
        first_cleaning_df['Job Title'].str.contains(role, case=False, na=False),'Roles'
    ] = role

/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/3294897196.py:15: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  first_cleaning_df['Job Title'].str.contains(role, case=False, na=False),'Roles'
/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/3294897196.py:15: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  first_cleaning_df['Job Title'].str.contains(role, case=False, na=False),'Roles'
/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/3294897196.py:15: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  first_cleaning_df['Job Title'].str.contains(role, case=False, na=False),'Roles'

In [4]:
#step for job sectors
# Define common sectors/industries to search for in the job responsibilities
sectors_industries = [
    'Technology', 'Finance', 'Retail', 'Manufacturing',
    'Consulting', 'Government', 'Nonprofit', 'Energy',
    'Real Estate', 'Biotech'
]
first_cleaning_df['Sector/Industry'] = 'Not Specified'
# Extract sector/industry information from job responsibilities if present
for sector in sectors_industries:
    first_cleaning_df.loc[jobs_df['Job Responsibilities/Duties'].str.contains(sector, case=False, na=False), 'Sector/Industry'] = sector

# Clean up the 'Job Responsibilities/Duties' column by removing the sector/industry keywords
first_cleaning_df['Job Responsibilities/Duties'] = first_cleaning_df['Job Responsibilities/Duties'].replace(
    '|'.join(sectors_industries), '', regex=True).str.strip()

In [5]:
#step for job type
job_types_to_extract = ['Full-Time', 'Part-Time', 'Contract', 'Internship','Full Time','Part Time']

first_cleaning_df['Job Type'] = 'Not Specified'
for job_type in job_types_to_extract:
    first_cleaning_df.loc[jobs_df['Job Responsibilities/Duties'].str.contains(job_type, case=False, na=False), 'Job Type'] = job_type

first_cleaning_df['Job Responsibilities/Duties'] = jobs_df['Job Responsibilities/Duties'].replace(
    '|'.join(job_types_to_extract), '', regex=True).str.strip()

jobs_df['Job Type'] = jobs_df['Job Type'].replace({
    'Part-Time': 'Part Time',
    'Full-Time': 'Full Time'
})

jobs_df['Job Type'].unique()

array(['Not Specified', 'Contract', 'Full Time', 'Part Time',
       'Internship'], dtype=object)

In [6]:
#step for salary
import re
salary = [
    r'\$\d{1,3}(?:,\d{3})*(?:\.\d{2})?',  
    r'\$\d+k',  
    r'\d+\s*per\s*hour',  
    r'\d+\s*-\s*\d+\s*(?:USD|dollars|per year|annual)'  
    r'\$\d{1,3}(?:,\d{3})*(?:\s*-?\s*\$\d{1,3}(?:,\d{3})*)?', 
    r'\$\d+\s*-\s*\d+k',  
    r'\$\d+\s*(?:per\s*month|per\s*week)', 
    r'\$\d+(?:,\d{3})*\s*(?:and\s*up|or\s*more|plus)'  

]
first_cleaning_df['Salary'] = 'Not Specified'

for index, row in first_cleaning_df.iterrows():
    text = row['Job Responsibilities/Duties']
    if pd.isna(text):
        continue  
    for pattern in salary:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            first_cleaning_df.at[index, 'Salary'] = match.group(0)
            break

In [7]:
#step for experience level

first_cleaning_df['Experience Level'] = 'Not Specified'
for index, row in first_cleaning_df.iterrows():
    text = row['Job Responsibilities/Duties']
    if pd.isna(text):
        continue  

  
    if re.search(r'\bentry\s*level\b|\bfresh\b|\bno experience\b', text, re.IGNORECASE):
        first_cleaning_df.at[index, 'Experience Level'] = 'Entry-Level'
    elif re.search(r'\bmid\b|\bmid\s*level\b|\bintermediate\b', text, re.IGNORECASE):
        first_cleaning_df.at[index, 'Experience Level'] = 'Mid-Level'
    elif re.search(r'\bsenior\b|\bexpert\b|\blead\b|\badvanced\b', text, re.IGNORECASE):
        first_cleaning_df.at[index, 'Experience Level'] = 'Senior-Level'
    else:
        
        first_cleaning_df.at[index, 'Experience Level'] = first_cleaning_df.at[index, 'Experience Level']

In [8]:
#step for education level
education_levels = ['Bachelor', 'Master', 'PhD', 'Diploma']
first_cleaning_df['Education Requirements'] = 'Not Specified'
for level in education_levels:
    first_cleaning_df.loc[first_cleaning_df['Job Responsibilities/Duties'].str.contains(level, case=False, na=False), 'Education Requirements'] = level

first_cleaning_df['Job Responsibilities/Duties'] = first_cleaning_df['Job Responsibilities/Duties'].replace(
    '|'.join(education_levels), '', regex=True).str.strip()

In [9]:
#step for experience years
experience_years = r'\b(\d{1,2})\s*(?:\+?\s*years?|-\s*\d{1,2}\s*years?|years? of experience|years? experience|years? required|years? minimum|at least \d{1,2} years?)'

for index, row in first_cleaning_df.iterrows():
    text = row['Job Responsibilities/Duties']
    if pd.isna(text):
        continue  

    match = re.search(experience_years, text, re.IGNORECASE)
    if match:
        first_cleaning_df.at[index, 'Required Years of Experience'] = match.group(1)

first_cleaning_df['Job Responsibilities/Duties'] = first_cleaning_df['Job Responsibilities/Duties'].replace(
    experience_years, '', regex=True).str.strip()

In [10]:
# step for remote option
remote_keywords = {
    'Remote': ['remote', 'work from home'],
    'On-site': ['on-site', 'in-office', 'in person'],
    'Hybrid': ['hybrid']
}

first_cleaning_df['Remote Work Options'] = 'Not Specified'

for index, row in first_cleaning_df.iterrows():
    text = row['Job Responsibilities/Duties']
    if pd.isna(text):
        continue 
    
    for option, keywords in remote_keywords.items():
        if any(re.search(r'\b' + keyword + r'\b', text, re.IGNORECASE) for keyword in keywords):
            first_cleaning_df.at[index, 'Remote Work Options'] = option
            break

In [11]:
# step for skills
skills_list = [
    'Python', 'C++', 'SQL', 'R', 'Machine Learning','Java','C/C++'
]

first_cleaning_df['Skills/Technologies Required'] = 'Not Specified'

for index, row in first_cleaning_df.iterrows():
    text = row['Job Responsibilities/Duties']
    if pd.isna(text):
        continue  
    
    extracted_skills = [skill for skill in skills_list if re.search(r'\b' + re.escape(skill) + r'\b', text, re.IGNORECASE)]
    if extracted_skills:
        first_cleaning_df.at[index, 'Skills/Technologies Required'] = ', '.join(extracted_skills)

In [12]:
#step for certification
certifications_list = [
    'AWS Certified',  'PMP',
]

first_cleaning_df['Certifications Required or Preferred'] = 'Not Specified'

for index, row in first_cleaning_df.iterrows():
    text = row['Job Responsibilities/Duties']
    if pd.isna(text):
        continue 
    
    extracted_certifications = [cert for cert in certifications_list if re.search(r'\b' + re.escape(cert) + r'\b', text, re.IGNORECASE)]
    if extracted_certifications:
        first_cleaning_df.at[index, 'Certifications Required or Preferred'] = ', '.join(extracted_certifications)

In [13]:
# step for visa eligilbity
visa_keywords = ['Citizen', 'Green Card', 'US Citizen', 'Permanent Resident', 'Resident','Citizenship','Green card','Visa','Sponsorship','Visa Sponsorship']

first_cleaning_df['Visa Sponsorship Availability'] = 'yes'


first_cleaning_df.loc[
    first_cleaning_df['Job Responsibilities/Duties'].str.contains('|'.join(visa_keywords), case=False, na=False),
    'Visa Sponsorship Availability'
] = 'no'

In [14]:
#step for shift type
shift_keywords = {
    'Day Shift': ['day shift', 'regular hours'],
    'Night Shift': ['night shift','evening shift','late'],
    'Flexible': ['flexible', 'flexible hours', 'anytime']
}

first_cleaning_df['Working Hours/Shift Type'] = 'Not Specified'

for index, row in first_cleaning_df.iterrows():
    text = row['Job Responsibilities/Duties']
    if pd.isna(text):
        continue  
    
    for shift_type, keywords in shift_keywords.items():
        if any(re.search(r'\b' + re.escape(keyword) + r'\b', text, re.IGNORECASE) for keyword in keywords):
            first_cleaning_df.at[index, 'Working Hours/Shift Type'] = shift_type
            break

In [15]:
df1 = first_cleaning_df
df1['Certifications Required or Preferred'] = df1['Certifications Required or Preferred'].replace('Not Specified', 'not required')
df1['Working Hours/Shift Type'] = df1['Working Hours/Shift Type'].replace('Not Specified', 'not mentioned')
df1['Remote Work Options'] = df1['Remote Work Options'].replace('Not Specified', 'not mentioned')
df1['Roles'] = df1['Roles'].replace('Not Specified', 'others')
df1['Sector/Industry'] = df1['Sector/Industry'].replace('Not Specified', 'others')

In [16]:
# Step 1: Missing Data Analysis
missing_data = df1.isin(["Not Specified", "not mentioned", ""]).sum().sort_values(ascending=False)
missing_data

Working Hours/Shift Type                584
Job Type                                524
Remote Work Options                     462
Salary                                  356
Required Years of Experience            247
Education Requirements                  228
Experience Level                        227
Skills/Technologies Required            195
Location                                  0
Roles                                     0
Job Responsibilities/Duties               0
Sector/Industry                           0
Company Name                              0
Job Description Length                    0
Certifications Required or Preferred      0
Visa Sponsorship Availability             0
Job Title                                 0
dtype: int64

In [17]:
df1.head(15)

,Job Title,Roles,Company Name,Sector/Industry,Location,Job Type,Salary,Experience Level,Education Requirements,Skills/Technologies Required,Job Responsibilities/Duties,Required Years of Experience,Remote Work Options,Job Description Length,Certifications Required or Preferred,Visa Sponsorship Availability,Working Hours/Shift Type
0,Technical Solutions Specialist,Specialist,Figure Eight Federal,Government,United States,Not Specified,Not Specified,Not Specified,Bachelor,Machine Learning,Artificial Intelligence (AI) is transforming g...,Not Specified,On-site,3738,not required,no,not mentioned
1,AI API specialist to integrate TypingMind into...,Specialist,Upwork,others,Anywhere,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,i have purchased and API code and such from Ty...,Not Specified,not mentioned,379,not required,yes,not mentioned
2,"Solutions Architect, Generative AI Specialist",Specialist,2100 NVIDIA USA,Technology,United States,Not Specified,Not Specified,Senior-Level,Not Specified,"Python, Machine Learning",Do you want to be part of the team that brings...,5,not mentioned,5140,not required,yes,not mentioned
3,"Machine Learning Specialist, Trilogy (Remote)",Specialist,Crossover,others,Anywhere,Not Specified,Not Specified,Senior-Level,Master,"Python, Machine Learning",Ready to leverage your mastery of LLMs to driv...,3,not mentioned,2786,not required,yes,not mentioned
4,Expert AI/Machine Learning Specialist Needed,Specialist,Upwork,others,Anywhere,Not Specified,Not Specified,Senior-Level,Not Specified,Machine Learning,We are seeking a highly rated expert in AI and...,Not Specified,not mentioned,480,not required,yes,not mentioned
5,AI and Information Security Analyst,others,RAND,Government,United States,Not Specified,"$192,100",Senior-Level,Master,"Python, R, Machine Learning, Java","RAND's Meselson Center, part of the Global and...",10,Remote,7433,not required,no,not mentioned
6,AI Language Specialist,Specialist,Outlier,others,"Air Force Academy, CO",Not Specified,$15,Not Specified,Not Specified,Not Specified,Outlier is seeking skilled writers proficient ...,Not Specified,Remote,1073,not required,yes,Flexible
7,"HPC/AI Sales Specialist, Federal",Specialist,HPE,others,California (+1 other),Contract,"$139,700.00",Mid-Level,Bachelor,Not Specified,"HPC/AI Sales Specialist, Federal\n\nThis role ...",4,Remote,7804,not required,no,not mentioned
8,AI specialist to setup make.com scenarios to p...,Specialist,Upwork,others,Anywhere,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,"Hello Upworkers,\n\nWe are seeking a Make.com ...",Not Specified,not mentioned,547,not required,yes,not mentioned
9,PPM Data Scientist/Statistician I,Statistician,ProSidian Consulting,Energy,"Boulder, CO",Contract,$18,Senior-Level,Bachelor,"Python, SQL, R",Company Description\n\nProSidian is a Manageme...,2,not mentioned,13393,not required,no,Flexible
10,Business Data Analyst for Financial Modeling S...,Data Analyst,Intelagile,Finance,United States,Not Specified,Not Specified,Not Specified,Bachelor,"Python, SQL, Machine Learning",Edit\n\nJob Duties:\n\nThe position serves as ...,Not Specified,not mentioned,1846,not required,no,Flexible
11,Data Analyst,Data Analyst,Nesco Resource,others,Anywhere,Not Specified,Not Specified,Not Specified,Master,"Python, SQL",Job Brief:\n\nJoin the Foundational Analytics ...,4,not mentioned,3520,not required,yes,not mentioned
12,Data Scientist Co-Op – Construction & Engineer...,Data Scientist,Oracle,Energy,United States,Not Specified,Not Specified,Not Specified,Master,"Python, SQL",Data Scientist Co-Op – Construction & Engineer...,40,Remote,6322,not required,yes,Flexible
13,Data Scientist/Analyst (India),Data Scientist,PayZen,Technology,Anywhere,Not Specified,Not Specified,Senior-Level,Master,Machine Learning,PayZen is on a mission to bring financial heal...,3,not mentioned,3338,not required,yes,not mentioned
14,Counterparty Data Analyst,Data Analyst,Insight Global,others,United States,Not Specified,Not Specified,Not Specified,Bachelor,SQL,Required Skills\n• 's degree\n• 3 to of data ...,6,not mentioned,2793,not required,yes,Flexible

In [18]:
# additional steps for required experience
import numpy as np
# Replace 'Not Specified' with NaN
jobs_df["Required Years of Experience"] = jobs_df["Required Years of Experience"].replace("Not Specified", np.nan)
# Convert the column to numeric, coercing any non-numeric values to NaN (although we've handled 'Not Specified' already)
jobs_df["Required Years of Experience"] = pd.to_numeric(jobs_df["Required Years of Experience"], errors='coerce')
#print(jobs_df["Required Years of Experience"].describe())

# some values are unrealisitic, this might due to misdescription or lack of detection,
#so unrealistics values will be removed, thres hold will be above ten years(my thoughts on senior level position might be 10 years)
jobs_df = jobs_df[(jobs_df["Required Years of Experience"] <= 10) | (jobs_df["Required Years of Experience"].isna())]
#print(jobs_df["Required Years of Experience"].describe())

# for na values, it means that it is not mentioned, so it can mean that years of experience might be not required
# so i will also cout these as 0
jobs_df["Required Years of Experience"].fillna(0, inplace=True)

/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/1576822606.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  jobs_df["Required Years of Experience"].fillna(0, inplace=True)
/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/1576822606.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jobs_df["Required Years of Experience"].fillna(0, inplace=True)

In [19]:
jobs_df.dtypes

Job Title                                object
Roles                                    object
Company Name                             object
Sector/Industry                          object
Location                                 object
Job Type                                 object
Salary                                   object
Experience Level                         object
Education Requirements                   object
Skills/Technologies Required             object
Job Responsibilities/Duties              object
Required Years of Experience            float64
Remote Work Options                      object
Job Description Length                    int64
Certifications Required or Preferred     object
Visa Sponsorship Availability            object
Working Hours/Shift Type                 object
dtype: object

In [20]:
# additional steps for salary
# some salary is in range, for this values it will be transformed by mean of the range
# for hourly and monthly, it will be converted as yearly, hourly assumes working 40 hours a week.
# Replace 'Not Specified' with NaN in Salary and remove non-numeric characters
# Reload the data again to reset and clean without labeling salary types explicitly

# Clean initial data by replacing 'Not Specified' and removing any non-numeric characters

jobs_df["Salary"] = jobs_df["Salary"].replace("Not Specified", np.nan)
jobs_df["Salary"] = jobs_df["Salary"].str.replace('[\$,]', '', regex=True)

# Handle salary ranges
for idx, salary in jobs_df["Salary"].dropna().items():
    if '-' in salary:
        low_salary, high_salary = salary.split('-')
        low_salary = float(low_salary.replace(",", "").strip())
        high_salary = float(high_salary.replace(",", "").strip())
        jobs_df.at[idx, "Salary"] = (low_salary + high_salary) / 2  # Replace with mean of range

# Convert the "Salary" column to numeric
jobs_df["Salary"] = pd.to_numeric(jobs_df["Salary"], errors='coerce')

# Convert hourly salaries to annual (assume values under 1000 are hourly)
jobs_df.loc[jobs_df["Salary"] < 1000, "Salary"] *= 40 * 52

# Convert monthly salaries to annual (assume values between 1000 and 10000 are monthly)
jobs_df.loc[jobs_df["Salary"].between(1000, 10000), "Salary"] *= 12

<>:10: SyntaxWarning: invalid escape sequence '\$'
<>:10: SyntaxWarning: invalid escape sequence '\$'
/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/21904052.py:10: SyntaxWarning: invalid escape sequence '\$'
  jobs_df["Salary"] = jobs_df["Salary"].str.replace('[\$,]', '', regex=True)
/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/21904052.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jobs_df["Salary"] = jobs_df["Salary"].replace("Not Specified", np.nan)
/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/21904052.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jobs_df["Salary"] = jobs_df["Salary"].str.replace('[\$,]', '', regex=True)
/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/21904052.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jobs_df["Salary"] = pd.to_numeric(jobs_df["Salary"], errors='coerce')

In [21]:
jobs_df["Salary"] = jobs_df["Salary"].replace(np.nan,"Not Specified")
jobs_df.tail(20)

/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/799929627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jobs_df["Salary"] = jobs_df["Salary"].replace(np.nan,"Not Specified")

,Job Title,Roles,Company Name,Sector/Industry,Location,Job Type,Salary,Experience Level,Education Requirements,Skills/Technologies Required,Job Responsibilities/Duties,Required Years of Experience,Remote Work Options,Job Description Length,Certifications Required or Preferred,Visa Sponsorship Availability,Working Hours/Shift Type
756,Masters Statistician Intern,Statistician,100 Eli Lilly and Company,others,United States,Internship,Not Specified,Senior-Level,Master,R,"At Lilly, we unite caring with discovery to ma...",0.0,not mentioned,5391,not required,yes,not mentioned
757,Consultant,Consultant,US101 Guidehouse Inc.,Government,United States,Not Specified,Not Specified,Senior-Level,Not Specified,"Python, R, Machine Learning",Job Family: Data Science Travel Required: Up ...,0.0,not mentioned,7244,not required,no,Flexible
758,Payments Fraud Analytics and Data Science Seni...,Consultant,Deloitte,Consulting,"Denver, CO",Not Specified,107659.0,Senior-Level,Bachelor,"Python, SQL, Machine Learning",Senior Consultant - Payments Fraud Analytics a...,4.0,not mentioned,7140,not required,no,not mentioned
759,Data and Analytics Management Consultant,Consultant,Point B,Consulting,"Denver, CO",Not Specified,105000.0,Senior-Level,Not Specified,"Python, SQL, R",Point B is a consulting firm that is trusted b...,8.0,Remote,9014,not required,yes,Flexible
760,AI/ML Health Data Science Consultant,Consultant,US101 Guidehouse Inc.,Consulting,United States,Not Specified,Not Specified,Not Specified,Master,"Python, SQL, R, Machine Learning",Job Family: Data Science Travel Required: Up ...,1.0,not mentioned,5843,not required,no,Flexible
761,"Data Scientist ::Primarily remote, 1-2 times a...",Data Scientist,SmartIPlace,others,Anywhere,Not Specified,Not Specified,Not Specified,Not Specified,"Python, Machine Learning",Summary: CareFirst is looking for a Machine Le...,6.0,not mentioned,713,not required,yes,not mentioned
762,Data Engineering Consultant,Consultant,Blue Margin,Consulting,Anywhere,Not Specified,156000.0,Mid-Level,Bachelor,"Python, SQL","About Us:\n\nAt Blue Margin, we are on a missi...",2.0,not mentioned,4632,not required,no,not mentioned
763,Data Reporting and Analytics Consultant,Consultant,Kaiser Permanente,others,"Denver, CO",Not Specified,Not Specified,Senior-Level,Bachelor,SQL,"At Kaiser Permanente, we believe that data sho...",3.0,not mentioned,1538,not required,yes,not mentioned
765,Data Analytics Consultant with S/4 HANA exp. (...,Consultant,RGP,Consulting,Anywhere,Not Specified,135200.0,Not Specified,Not Specified,Not Specified,As a Data Analytics Consultant with SAP S/4 HA...,0.0,Remote,3797,not required,yes,not mentioned
766,AI/ML Health Data Scientist Senior Consultant,Consultant,US101 Guidehouse Inc.,Consulting,United States,Contract,Not Specified,Senior-Level,Bachelor,"Python, SQL, R, Machine Learning",Job Family: Data Science Travel Required: Up ...,3.0,not mentioned,7067,not required,no,Flexible
767,Data architect,Data Architect,Capital One,Technology,"Yorkana, PA",Part Time,274800.0,Senior-Level,Master,"Python, SQL, Machine Learning","Center 1 (19052), United States of America, Mc...",7.0,On-site,8025,not required,no,not mentioned
768,Data Architect,Data Architect,Arkansas Department of Workforce Services,Technology,"Elkins, AR",Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,This job was posted by https://www.arjoblink.a...,0.0,not mentioned,2568,not required,yes,not mentioned
769,Data Architect,Data Architect,Virginia Tech,Technology,"Blacksburg, VA",Not Specified,1040000.0,Not Specified,Bachelor,Python,Job Description\n\nThe office of Analytics and...,0.0,not mentioned,4671,not required,yes,not mentioned
770,Sr Data Architect I,Data Architect,"Staples, Inc.",Retail,"Framingham, MA",Not Specified,Not Specified,Senior-Level,Master,Python,Staples is business to business. You’re what b...,7.0,not mentioned,3770,not required,yes,Flexible
771,Principal Data Architect (Intelligence Center),Data Architect,The MITRE Corporation,Government,"McLean, VA (+2 others)",Not Specified,157000.0,Senior-Level,Master,R,Why choose between doing meaningful work and h...,10.0,On-site,5877,not required,yes,not mentioned
772,Principal Data Architect,Data Architect,Disney Experiences,Technology,"Seattle, WA (+3 others)",Not Specified,180700.0,Senior-Level,Master,Machine Learning,“We Power the Magic!” That’s our motto at Disn...,10.0,not mentioned,4775,not required,yes,not mentioned
773,Senior Data Architect,Data Architect,Beacon Hill,Finance,"Waukegan, IL",Not Specified,Not Specified,Senior-Level,Master,Python,Qualifications:\n\n·'s degree and of experien...,2.0,not mentioned,4203,not required,yes,not mentioned
774,Data Architect,Data Architect,EY,Energy,"Irvine, CA",Not Specified,105800.0,Senior-Level,Not Specified,"Python, SQL, Machine Learning","At EY, you’ll have the chance to build a caree...",0.0,On-site,9709,not required,yes,Flexible
775,Senior Cloud Data Solutions Architect,others,Truist Bank,Technology,"Atlanta, GA (+4 others)",Part Time,Not Specified,Senior-Level,Bachelor,"Python, SQL, R, Machine Learning, Java",The position is described below. If you want t...,8.0,not mentioned,9039,not required,no,not mentioned
776,Data Architect,Data Architect,Clean Harbors,Energy,"Rockland, MA",Not Specified,Not Specified,Senior-Level,Master,"Python, SQL, Machine Learning, Java","At Clean Harbors, we are seeking a highly skil...",10.0,On-site,7535,not required,yes,not mentioned

In [22]:
#potential inconsistency problem for location,job type,sector/industry
jobs_df['Job Type'] = jobs_df['Job Type'].replace({
    'Part Time': 'Part-Time',
    'Full Time': 'Full-Time'
})

# Remove location modifiers like "(+1 other)" and "(+2 others)" from the "Location" column
jobs_df['Location'] = jobs_df['Location'].str.replace(r'\s\(\+\d+\sothers?\)', '', regex=True)

# Standardize "others" in "Sector/Industry" for clarity
jobs_df['Sector/Industry'] = jobs_df['Sector/Industry'].replace({'others': 'Other'})

/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/3033478737.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jobs_df['Job Type'] = jobs_df['Job Type'].replace({
/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/3033478737.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jobs_df['Location'] = jobs_df['Location'].str.replace(r'\s\(\+\d+\sothers?\)', '', regex=True)
/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/3033478737.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jobs_df['Sector/Industry'] = jobs_df['Sector/Industry'].replace({'others': 'Other'})

In [23]:
# divide location column to state and city and create column state and city
jobs_df[['City', 'State']] = jobs_df['Location'].str.extract(r'^(.*?),\s*([A-Z]{2})$', expand=True)
columns_order = list(jobs_df.columns)
location_index = columns_order.index('Location')
reordered_columns = columns_order[:location_index + 1] + ['City', 'State'] + columns_order[location_index + 1:-2]
jobs_df = jobs_df[reordered_columns]


# if city and state has no value it will have not specified value
jobs_df['City'].fillna('Not Specified', inplace=True)
jobs_df['State'].fillna('Not Specified', inplace=True)
jobs_df.head()

/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/3389611169.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jobs_df[['City', 'State']] = jobs_df['Location'].str.extract(r'^(.*?),\s*([A-Z]{2})$', expand=True)
/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/3389611169.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jobs_df[['City', 'State']] = jobs_df['Location'].str.extract(r'^(.*?),\s*([A-Z]{2})$', expand=True)
/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/3389611169.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  jobs_df['City'].fillna('Not Specified', inplace=True)
/var/folders/h9/km0tr_g527jd0vmrgtmb46g00000gn/T/ipykernel_12936/3389611169.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  jobs_df['State'].fillna('Not Specified', inplace=True)

,Job Title,Roles,Company Name,Sector/Industry,Location,City,State,Job Type,Salary,Experience Level,Education Requirements,Skills/Technologies Required,Job Responsibilities/Duties,Required Years of Experience,Remote Work Options,Job Description Length,Certifications Required or Preferred,Visa Sponsorship Availability,Working Hours/Shift Type
0,Technical Solutions Specialist,Specialist,Figure Eight Federal,Government,United States,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Bachelor,Machine Learning,Artificial Intelligence (AI) is transforming g...,0.0,On-site,3738,not required,no,not mentioned
1,AI API specialist to integrate TypingMind into...,Specialist,Upwork,Other,Anywhere,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,Not Specified,i have purchased and API code and such from Ty...,0.0,not mentioned,379,not required,yes,not mentioned
2,"Solutions Architect, Generative AI Specialist",Specialist,2100 NVIDIA USA,Technology,United States,Not Specified,Not Specified,Not Specified,Not Specified,Senior-Level,Not Specified,"Python, Machine Learning",Do you want to be part of the team that brings...,5.0,not mentioned,5140,not required,yes,not mentioned
3,"Machine Learning Specialist, Trilogy (Remote)",Specialist,Crossover,Other,Anywhere,Not Specified,Not Specified,Not Specified,Not Specified,Senior-Level,Master,"Python, Machine Learning",Ready to leverage your mastery of LLMs to driv...,3.0,not mentioned,2786,not required,yes,not mentioned
4,Expert AI/Machine Learning Specialist Needed,Specialist,Upwork,Other,Anywhere,Not Specified,Not Specified,Not Specified,Not Specified,Senior-Level,Not Specified,Machine Learning,We are seeking a highly rated expert in AI and...,0.0,not mentioned,480,not required,yes,not mentioned

In [24]:
#from datatypes, it is needed to change salary and potentially required years of experience(since there is no decimal point for this)
jobs_df.dtypes
jobs_df['Salary'] = pd.to_numeric(jobs_df['Salary'], errors='coerce')
jobs_df['Required Years of Experience'] = jobs_df['Required Years of Experience'].fillna(0).astype(int)
jobs_df.dtypes

#for handling na value in salary column, one idea could be imputing median salary by experience level
jobs_df['Salary'] = jobs_df.groupby('Experience Level')['Salary'].transform(lambda x: x.fillna(x.median()))

In [25]:
# save it as csv file
jobs_df.to_csv('/Users/zp/hw-3-zp199717/data/processed-jobs-1.csv', index=False)